import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./components/layout";
import { SelectedLinkProvider } from "./selectedlinkprovider";
import { auth } from "@/app/api/auth/[...nextauth]/route";
import {SessionProvider} from "next-auth/react"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
   <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
       <SelectedLinkProvider>
        <Layout>
          {children}
          </Layout>
       </SelectedLinkProvider>
        </body>
    </html>
    </SessionProvider>
  );
}


